server:
  port: 8070

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: dadata-service
          uri: lb://dadata-service
          predicates:
            - Path=/search/**